# backend:
#  name: github
#  repo: rwietter/rwietter.dev
#  branch: main
#  squash_merges: true ## Estrategia de juntar todos commits em um quando publicar
#  base_url: https://rwietterc.xyz/
#  auth_endpoint: api/auth/ ## Endpoint para autenticação com git
#  use_graphql: true
backend:
 name: git-gateway
 branch: main

site_url: https://rwietterc.xyz/

media_folder: public/assets/img
public_folder: /assets/img
publish_mode: editorial_workflow # Isso permite ter aquele workflow com drafts e tudo

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: posts 
    label: posts 
    folder: posts # A pasta onde ficarão os posts
    create: true # Permite criar um post novo
    slug: '{{slug}}' # Estrutura do nome arquivo, exemplo: title.md
    fields: # Os campos do seu frontmatter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss'
        }
      - { label: 'Post Image', name: 'image', widget: 'image', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }

      - { label: 'Body', name: 'body', widget: 'markdown' }