# example config.yml: https://github.com/decaporg/decap-cms/blob/main/dev-test/config.yml

backend:
  name: git-gateway
  branch: main
  repo: rwietter/rwietter.xyz
  site_domain: https://rwietter.xyz
  auth_endpoint: api/auth/
  base_url: https://rwietter.xyz

media_folder: public/assets/img
public_folder: /assets/img
publish_mode: editorial_workflow
show_preview_links: true
media_library:
  name: cloudinary
  config:
    cloud_name: ddwnioveu
    api_key: 452859833286493
    multiple: false

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: posts
    label: posts
    folder: public/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Slug", name: "slug", widget: "string", required: true }
      - {
          label: "Category",
          name: "category",
          widget: "string",
          required: true,
        }
      - {
          label: "Date",
          name: "publishedAt",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Post Image", name: "image", widget: "image", required: true }
      - {
          label: "Alternative Text",
          name: "alternativeText",
          widget: "string",
          required: true,
        }
      - { label: "Caption", name: "caption", "widget": "string" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
