backend:
  name: git-gateway
  branch: main
  repo: rwietter/rwietter.dev
  site_domain: https://rwietter.netlify.app
  auth_endpoint: api/auth/
  base_url: https://rwietter.netlify.app

media_folder: public/assets/img
public_folder: /assets/img
publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: posts
    label: posts
    folder: public/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Slug", name: "slug", widget: "string", required: true }
      - {
          label: "Category",
          name: "category",
          widget: "string",
          required: true,
        }
      - {
          label: "Date",
          name: "publishedAt",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Post Image", name: "image", widget: "image", required: true }
      - {
          label: "Alternative Text",
          name: "alternativeText",
          widget: "string",
          required: true,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
